name: CI

on:
  pull_request:
    branches: [main]

jobs:
  smoke:
    name: Smoke test (docs build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: pnpm i
      - run: pnpm build
      - run: pnpm build:docs
