name: CI

on:
  pull_request:
    branches: [main]

jobs:
  smoke:
    name: Smoke test (docs build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20.19.5
      - run: pnpm i
      - run: pnpm build
      - run: pnpm build:docs
